# Generated by Django 3.0.1 on 2020-01-03 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disjuntor',
            name='dj',
            field=models.DecimalField(decimal_places=0, max_digits=3, verbose_name='Mini DJ Schneider'),
        ),
    ]
