# Generated by Django 3.0.1 on 2020-01-03 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cable', '0002_auto_20200103_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disjuntor',
            name='dj',
            field=models.CharField(max_length=4, verbose_name='Mini DJ Schneider'),
        ),
    ]
