# Generated by Django 3.0.1 on 2020-01-03 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cable', '0003_auto_20200103_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabelacondutor',
            name='capacidade_conducao',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Capacidade de Condução'),
        ),
    ]
