# Generated by Django 3.0.1 on 2020-01-03 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cable', '0006_auto_20200103_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residencdimens',
            name='tensa_va',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cable.Tensao', verbose_name='Tensão (VA)'),
        ),
    ]
