# Generated by Django 3.0.1 on 2020-01-03 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cable', '0008_auto_20200103_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tensao',
            name='volts',
            field=models.CharField(max_length=10),
        ),
    ]
